Updates error messages for Artifactory and git-credentials

diff --git a/tasks/2-build-tag-push.yaml b/tasks/2-build-tag-push.yaml
--- a/tasks/2-build-tag-push.yaml
+++ b/tasks/2-build-tag-push.yaml
@@ -50,6 +50,11 @@ spec:
         - |
           set -e
 
+          if [[ -z "$GIT_AUTH_USER" ]] || [[ -z "$GIT_AUTH_PWD" ]]; then
+            echo "Git credentials not found. The pipeline expects to find them in a secret named 'git-credentials'."
+            echo "  Update your CLI and register the pipeline again"
+            exit 1
+          fi
           git config --local credential.helper "!f() { echo username=$GIT_AUTH_USER; echo password=$GIT_AUTH_PWD; }; f"
 
           echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
diff --git a/tasks/6-helm-package.yaml b/tasks/6-helm-package.yaml
--- a/tasks/6-helm-package.yaml
+++ b/tasks/6-helm-package.yaml
@@ -151,24 +151,19 @@ spec:
 
           . ./env-config
 
-          if [[ -z "${ARTIFACTORY_ENCRYPT}" ]]; then
-            echo "ARTIFACTORY_ENCRYPT is required from secret artifactory-access"
-            exit 0
-          fi
-
-          if [[ -z "${ARTIFACTORY_USER}" ]]; then
-            echo "ARTIFACTORY_USER is required from secret artifactory-access"
-            exit 0
-          fi
-
-          if [[ -z "${ARTIFACTORY_PASSWORD}" ]]; then
-            echo "ARTIFACTORY_PASSWORD is required from secret artifactory-access"
-            exit 0
-          fi
-
           if [[ -z "${ARTIFACTORY_URL}" ]]; then
-            echo "ARTIFACTORY_URL is required from config map artifactory-config"
+            echo "It looks like Artifactory has not been installed (ARTIFACTORY_URL from artifactory-config config map is missing). Skipping step."
             exit 0
+          fi
+
+          if [[ -z "${ARTIFACTORY_USER}" ]] || [[ -z "${ARTIFACTORY_PASSWORD}" ]]; then
+            echo "Something's wrong... The Artifactory url is configured but the Artifactory credentials cannot be found. Check your artifactory-access secret."
+            exit 1
+          fi
+
+          if [[ -z "${ARTIFACTORY_ENCRYPT}" ]]; then
+              echo "It looks like your Artifactory installation is not complete. Please complete the steps found here - http://ibm.biz/complete-setup"
+              exit 1
           fi
 
           IMAGE_URL=$(inputs.resources.image.url)
