Updates to tasks for ocp 4.3 (#6)
* Updates tekton tasks to manage build version number from git tags

* Updates java-gradle pipeline to inclure requried image resource

* Updates logic for sonarqube execution to test for the task first

* Fixes hard-coded dev branch reference

* Updates logic for release-it to tag the code and removes release-it dependency from deploy, helm-package, and gitops

* Updates logic for getting release tag in deploy, helm-package, and gitops

* updat tekton tasks to be in sync with kjenkins

* fix npm problem

Co-authored-by: Carlos Santana <csantana23@gmail.com>

diff --git a/tasks/3-deploy.yaml b/tasks/3-deploy.yaml
--- a/tasks/3-deploy.yaml
+++ b/tasks/3-deploy.yaml
@@ -15,18 +15,36 @@ spec:
         default: docker.io/node:12-stretch
       - name: tools-image
         type: string
-        default: docker.io/csantanapr/helm-kubectl
+        default: garagecatalyst/ibmcloud-dev:1.0.10
   steps:
     - name: setup
       image: $(inputs.params.js-image)
       workingdir: $(inputs.resources.source.path)
       command: ["/bin/bash"]
+      env:
+        - name: BRANCH
+          value: "$(inputs.resources.source.revision)"
       args:
         - -c
         - |
-          set -e
-          # Export project name
-          npm run env | grep "^npm_package_version" | sed "s/npm_package_version/APP_VERSION/g" >> ./env-config
+          set -x
+          set +e
+
+          git fetch origin ${BRANCH} --tags
+          git checkout ${BRANCH}
+
+          echo "IMAGE_VERSION=$(git describe --abbrev=0 --tags)" > ./env-config
+          echo "IMAGE_NAME=$(basename -s .git `git config --get remote.origin.url` | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')" >> ./env-config
+
+          source ./env-config
+          if [[ -z "${IMAGE_VERSION}" ]]; then
+              echo "Error: IMAGE_VERSION not defined"
+              exit 1
+          fi
+          if [[ -z "${IMAGE_NAME}" ]]; then
+              echo "Error: IMAGE_NAME not defined"
+              exit 1
+          fi
     - name: deploy
       image: $(inputs.params.tools-image)
       workingdir: $(inputs.resources.source.path)
@@ -52,34 +70,31 @@ spec:
 
           REGISTRY_URL=$(echo $IMAGE_URL | awk -F / '{print $1}')
           REGISTRY_NAMESPACE=$(echo $IMAGE_URL | awk -F / '{print $2}')
-          IMAGE_NAME=$(echo $IMAGE_URL | awk -F / '{print $3}' | awk -F : '{print $1}')
-          HASTAG=$(echo $IMAGE_URL | awk -F / '{print $3}' | awk -F : '{print NF-1}')
-          if [[ "$HASTAG" == "1"  ]]; then
-              IMAGE_VERSION=$(echo $IMAGE_URL | awk -F / '{print $3}' | awk -F : '{print $2}')
-          else
-              IMAGE_VERSION=latest
-          fi
-          echo $REGISTRY_URL
-          echo $REGISTRY_NAMESPACE
-          echo $IMAGE_VERSION
-          IMAGE_BUILD_VERSION="${APP_VERSION}-${IMAGE_VERSION}"
+
+          echo "REGISTRY_URL: $REGISTRY_URL"
+          echo "REGISTRY_NAMESPACE: $REGISTRY_NAMESPACE"
+          echo "IMAGE_NAME: $IMAGE_NAME"
+          echo "IMAGE_VERSION: $IMAGE_VERSION"
 
           export CHART_ROOT=$(find . -name chart)
-          echo $CHART_ROOT
+          echo "CHART_ROOT: $CHART_ROOT"
 
           export CHART=$(find . -name Chart\*)
-          echo $CHART
+          echo "CHART: $CHART"
 
           export CHART_NAME=$(cat $CHART | awk '/name:/ {print $2}')
-          echo $CHART_NAME
+          echo "CHART_NAME: $CHART_NAME"
 
           # Update Chart name and version
           if [[ "${CHART_NAME}" != "${IMAGE_NAME}" ]]; then
+            echo "Renaming chart from ${CHART_NAME} to ${IMAGE_NAME}"
             cp -R "${CHART_ROOT}/${CHART_NAME}" "${CHART_ROOT}/${IMAGE_NAME}"
             cat "${CHART_ROOT}/${CHART_NAME}/Chart.yaml" | \
                 yq w - apiVersion "v1" | \
                 yq w - name "${IMAGE_NAME}" | \
-                yq w - version "${APP_VERSION}" > "${CHART_ROOT}/${IMAGE_NAME}/Chart.yaml"
+                yq w - version "${IMAGE_VERSION}" > "${CHART_ROOT}/${IMAGE_NAME}/Chart.yaml"
+          else
+            echo "Chart name and image name match: ${IMAGE_NAME}"
           fi
 
           CHART_PATH="${CHART_ROOT}/${IMAGE_NAME}"
@@ -105,8 +120,10 @@ spec:
 
           # Update helm chart with repository and tag values
           cat ${CHART_PATH}/values.yaml | \
+              yq w - nameOverride "${IMAGE_NAME}" | \
+              yq w - fullnameOverride "${IMAGE_NAME}" | \
               yq w - image.repository "${IMAGE_REPOSITORY}" | \
-              yq w - image.tag "${IMAGE_BUILD_VERSION}" | \
+              yq w - image.tag "${IMAGE_VERSION}" | \
               yq w - ingress.enabled "${INGRESS_ENABLED}" | \
               yq w - route.enabled "${ROUTE_ENABLED}" > ./values.yaml.tmp
           cp ./values.yaml.tmp ${CHART_PATH}/values.yaml
diff --git a/tasks/4-health-check.yaml b/tasks/4-health-check.yaml
--- a/tasks/4-health-check.yaml
+++ b/tasks/4-health-check.yaml
@@ -15,7 +15,7 @@ spec:
         default: docker.io/node:12-stretch
       - name: tools-image
         type: string
-        default: docker.io/csantanapr/helm-kubectl
+        default: garagecatalyst/ibmcloud-dev:1.0.10
   steps:
     - name: health-check
       image: $(inputs.params.tools-image)
@@ -25,37 +25,30 @@ spec:
           valueFrom:
             fieldRef:
               fieldPath: metadata.namespace
+      envFrom:
+        - configMapRef:
+            name: ibmcloud-config
       command: ["/bin/bash"]
       args:
         - -c
         - |
           ENVIRONMENT_NAME="${NAMESPACE}"
 
-          IMAGE_URL=$(inputs.resources.image.url)
+          IMAGE_NAME=$(basename -s .git `git config --get remote.origin.url` | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')
 
-          REGISTRY_URL=$(echo $IMAGE_URL | awk -F / '{print $1}')
-          REGISTRY_NAMESPACE=$(echo $IMAGE_URL | awk -F / '{print $2}')
-          INGRESS_NAME=$(echo $IMAGE_URL | awk -F / '{print $3}' | awk -F : '{print $1}')
-
-          HOST=$(kubectl get ingress/${INGRESS_NAME} --namespace ${ENVIRONMENT_NAME} --output="jsonpath={ .spec.rules[0].host }")
-          PROTOCOL="http"
-
-          set -e
-          if [[ -z "${HOST}" ]]; then
-            HOST=$(kubectl get route/${INGRESS_NAME} --namespace ${ENVIRONMENT_NAME} --output="jsonpath={ .spec.host }")
-            PROTOCOL="https"
-            echo "Found route: ${HOST}"
+          if [[ "${CLUSTER_TYPE}" == "openshift" ]]; then
+              ROUTE_HOST=$(kubectl get route/${IMAGE_NAME} --namespace ${ENVIRONMENT_NAME} --output=jsonpath='{ .spec.host }')
+              URL="https://${ROUTE_HOST}"
           else
-            echo "Found ingress: ${HOST}"
+              INGRESS_HOST=$(kubectl get ingress/${IMAGE_NAME} --namespace ${ENVIRONMENT_NAME} --output=jsonpath='{ .spec.rules[0].host }')
+              URL="http://${INGRESS_HOST}"
           fi
-
           # sleep for 10 seconds to allow enough time for the server to start
           sleep 30
-
-          if [[ $(curl -sL -w "%{http_code}\\n" "${PROTOCOL}://${HOST}/health" -o /dev/null --connect-timeout 3 --max-time 5 --retry 3 --retry-max-time 30) == "200" ]]; then
-              echo "Successfully reached health endpoint: ${PROTOCOL}://${HOST}/health"
+          if [[ $(curl -sL -w "%{http_code}\\n" "${URL}/health" -o /dev/null --connect-timeout 3 --max-time 5 --retry 3 --retry-max-time 30) == "200" ]]; then
+              echo "Successfully reached health endpoint: ${URL}/health"
               echo "====================================================================="
           else
-              echo "Could not reach health endpoint: ${PROTOCOL}://${HOST}/health"
-              exit 1
-          fi
+              echo "Could not reach health endpoint: ${URL}/health"
+              exit 1;
+          fi;
