trivy scan with review corrections

diff --git a/tasks/3-img-scan-trivy.yaml b/tasks/3-img-scan-trivy.yaml
--- a/tasks/3-img-scan-trivy.yaml
+++ b/tasks/3-img-scan-trivy.yaml
@@ -3,8 +3,8 @@ kind: Task
 metadata:
   name: ibm-img-scan-trivy
   annotations:
-    description: Detects comprehensive vulnerabilities in the container image using Trivy.
-    app.openshift.io/description: Detects comprehensive vulnerabilities in the container image using Trivy.
+    description: Runs an image scan with Trivy and fails the build if issues are found.
+    app.openshift.io/description: Runs an image scan with Trivy and fails the build if issues are found.
     app.openshift.io/vcs-uri: https://github.com/IBM/ibm-garage-tekton-tasks
     app.openshift.io/vcs-ref: master
   labels:
@@ -16,14 +16,18 @@ spec:
     - name: scan-image
       description: Flag indicating that a scan should be performed
       default: "false"
-    - name: tools-image
+    - name: SKOPEO_IMAGE
+      default: quay.io/containers/skopeo:v1.1.0
+    - name: IMAGE_FROM_TLS_VERIFY
+      default: "false"
+    - name: TRIVY_IMAGE
       default: docker.io/aquasec/trivy
   volumes:
-    - name: source
+    - name: oci-image
       emptyDir: {}
   steps:
-    - name: scan-image-trivy
-      image: $(params.tools-image)
+    - name: pull-image
+      image: $(params.SKOPEO_IMAGE)
       env:
         - name: REGISTRY_USER
           valueFrom:
@@ -37,52 +41,49 @@ spec:
               name: ibmcloud-apikey
               key: APIKEY
               optional: true
-      command:
-        - /bin/sh
-      args:
-        - '-c'
-        - >
+      volumeMounts:
+        - mountPath: /var/oci
+          name: oci-image
+      securityContext:
+        privileged: true
+      script: |
+        PERFORM_SCAN="$(params.scan-image)"
+        if [[ "${PERFORM_SCAN}" == "false" ]] || [[ -z "${PERFORM_SCAN}" ]]; then
+          echo "User selected to skip scanning. Skipping Trivy scan."
+          exit 0
+        fi
+        IMAGE_FROM=$(params.image-url)
+        REGISTRY_SERVER_FROM=$(echo "${IMAGE_FROM}" | awk -F / '{print $1}')
+        IMAGE_TO="oci:/var/oci/image"
+        IMAGE_FROM_TLS_VERIFY=$(params.IMAGE_FROM_TLS_VERIFY)
+        echo "Tagging ${IMAGE_FROM} as ${IMAGE_TO}"
+        set +x
+        if [[ -n "${REGISTRY_USER}" ]] && [[ -n "${REGISTRY_PASSWORD}" ]] && [[ "${REGISTRY_SERVER_FROM}" != "image-registry.openshift-image-registry.svc:5000" ]]; then
+          IMAGE_FROM_CREDS="--src-creds ${REGISTRY_USER}:${REGISTRY_PASSWORD}"
+        fi
+        set -x
+        if [ "${REGISTRY_SERVER_FROM}" =~ ":" ]; then
+          IMAGE_FROM_TLS_VERIFY="false"
+        fi
+        echo "skopeo copy --src-creds=xxxx --src-tls-verify=${IMAGE_FROM_TLS_VERIFY} docker://${IMAGE_FROM} ${IMAGE_TO}"
+        set +x
+        skopeo copy ${IMAGE_FROM_CREDS} --src-tls-verify=${IMAGE_FROM_TLS_VERIFY} docker://${IMAGE_FROM} ${IMAGE_TO}
+    - name: scan-image
+      image: $(params.TRIVY_IMAGE)
+      volumeMounts:
+        - mountPath: /var/oci
+          name: oci-image
+      script: |
           set -e
-
-          IMAGE_URL=$(params.image-url)
-
-          REGISTRY_SERVER=$(echo $(params.image-url) | awk -F / '{print $1}')
-
-          PERFORM_SCAN="$(params.scan-image)"
-
-          if [[ "${PERFORM_SCAN}" == "false" ]] || [[ -z "${PERFORM_SCAN}" ]]; then
-
-            echo "User selected to skip scanning. Skipping Trivy scan ."
-
-            exit 0
-
-          fi
-
+          PATH_TO_IMAGE="/var/oci/image"
           echo -e "Trivy Security Scan image in registry"
-
-          echo "Registry URL: ${REGISTRY_SERVER}"
-
-          export TRIVY_AUTH_URL=${REGISTRY_SERVER}
-
-          export TRIVY_USERNAME=${REGISTRY_USER}
-
-          export TRIVY_PASSWORD=${REGISTRY_PASSWORD}
-
-
-          trivy image --exit-code 1 --severity CRITICAL ${IMAGE_URL}
-
+          trivy image --exit-code 0 --input ${PATH_TO_IMAGE}
+          trivy image --exit-code 1 --severity CRITICAL --input ${PATH_TO_IMAGE}
           my_exit_code=$?
-
           echo "Scan exit code :--- $my_exit_code"
-
           if [ ${my_exit_code} == 1 ]; then
-
-              echo "Failed : Trivy scanning completed. CRITICAL Vulnerabilities found.";
-
-              exit 1;
-
+              echo "Trivy scanning completed. CRITICAL Vulnerabilities found."
+              exit 1
           else
-
-            echo "Success : Trivy scanning completed. CRITICAL vulnerabilities not found."
-
-          fi;
+            echo "Trivy scanning completed. CRITICAL vulnerabilities not found."
+          fi
