Adds retry loop to health check

diff --git a/tasks/4-health-check.yaml b/tasks/4-health-check.yaml
--- a/tasks/4-health-check.yaml
+++ b/tasks/4-health-check.yaml
@@ -45,12 +45,19 @@ spec:
               INGRESS_HOST=$(kubectl get ingress/${IMAGE_NAME} --namespace ${ENVIRONMENT_NAME} --output=jsonpath='{ .spec.rules[0].host }')
               URL="http://${INGRESS_HOST}"
           fi
+
+          sleep_countdown=5
+
           # sleep for 10 seconds to allow enough time for the server to start
-          sleep 30
-          if [[ $(curl -sL -w "%{http_code}\\n" "${URL}/health" -o /dev/null --connect-timeout 3 --max-time 5 --retry 3 --retry-max-time 30) == "200" ]]; then
-              echo "Successfully reached health endpoint: ${URL}/health"
-              echo "====================================================================="
-          else
-              echo "Could not reach health endpoint: ${URL}/health"
-              exit 1;
-          fi;
+          sleep 10
+          while [ $(curl -sL -w "%{http_code}\\n" "${URL}/health" -o /dev/null --connect-timeout 3 --max-time 5 --retry 3 --retry-max-time 30) != "200" ]; do
+              sleep 30
+              sleep_countdown=$((sleep_countdown-1))
+              if [ sleep_countdown=0 ]; then
+                      echo "Could not reach health endpoint: ${URL}/health"
+                      exit 1;
+              fi
+          done
+
+          echo "Successfully reached health endpoint: ${URL}/health"
+          echo "====================================================================="
