Updates health check to look for route if ingress does not exist

diff --git a/tasks/4-health-check.yaml b/tasks/4-health-check.yaml
--- a/tasks/4-health-check.yaml
+++ b/tasks/4-health-check.yaml
@@ -39,16 +39,21 @@ spec:
           REGISTRY_NAMESPACE=$(echo $IMAGE_URL | awk -F / '{print $2}')
           INGRESS_NAME=$(echo $IMAGE_URL | awk -F / '{print $3}' | awk -F : '{print $1}')
 
-          INGRESS_HOST=$(kubectl get ingress/${INGRESS_NAME} --namespace ${ENVIRONMENT_NAME} --output=jsonpath='{ .spec.rules[0].host }')
+          set +e
+          HOST=$(kubectl get ingress/${INGRESS_NAME} --namespace ${ENVIRONMENT_NAME} --output=jsonpath='{ .spec.rules[0].host }')
+          set -e
+          if [[ -z "${HOST}" ]]; then
+            HOST=$(kubectl get route/${INGRESS_NAME} --namespace ${ENVIRONMENT_NAME} --output=jsonpath='{ .spec.host }')
+          fi
           PORT='80'
 
           # sleep for 10 seconds to allow enough time for the server to start
           sleep 30
 
-          if [ $(curl -sL -w "%{http_code}\\n" "http://${INGRESS_HOST}:${PORT}/health" -o /dev/null --connect-timeout 3 --max-time 5 --retry 3 --retry-max-time 30) == "200" ]; then
-              echo "Successfully reached health endpoint: http://${INGRESS_HOST}:${PORT}/health"
+          if [ $(curl -sL -w "%{http_code}\\n" "http://${HOST}:${PORT}/health" -o /dev/null --connect-timeout 3 --max-time 5 --retry 3 --retry-max-time 30) == "200" ]; then
+              echo "Successfully reached health endpoint: http://${HOST}:${PORT}/health"
               echo "====================================================================="
           else
-              echo "Could not reach health endpoint: http://${INGRESS_HOST}:${PORT}/health"
+              echo "Could not reach health endpoint: http://${HOST}:${PORT}/health"
               exit 1
           fi
