Support for building multiachitecture images using Tekton (#154)
* Updates for signed image setup script (#144)

* suppress newlines in echo

Signed-off-by: Tim Robinson <timroster@gmail.com>

* set rsa4096 algo for gpg

Signed-off-by: Tim Robinson <timroster@gmail.com>
Signed-off-by: Amine RACHYD <aminerachyd99@gmail.com>

* faciliate .trivyignore from git and add to nodejs pipeline (#148)

Signed-off-by: Brian Innes <binnes@uk.ibm.com>
Signed-off-by: Amine RACHYD <aminerachyd99@gmail.com>

* Updated pipelines and tasks

Added "grpc" protocol option (choice between https and grpc) in the
general pipeline.
Updated setup task to take docker image with grpc health check tool
(grpc_health_probe on github).
Added grpc check command in the health check task.

Signed-off-by: Amine RACHYD <aminerachyd99@gmail.com>

* Updated health check task, support for gRPC APIs

Signed-off-by: Amine RACHYD <aminerachyd99@gmail.com>

* Updated pipelines and tasks

Added "grpc" protocol option (choice between https and grpc) in the
general pipeline.
Updated setup task to take docker image with grpc health check tool
(grpc_health_probe on github).
Added grpc check command in the health check task.

Signed-off-by: Amine RACHYD <aminerachyd99@gmail.com>

* Removed versions from tasks/pipeline

Signed-off-by: Amine RACHYD <aminerachyd99@gmail.com>

* Started multiarch pipeline

The multiarch pipeline connects to other clusters in order to build
locally on them and produce images dependent on each architecture.
The "remote" clusters work like agents, where we run a single-task
pipeline.

Added some tasks used by the multiarch pipeline.

Signed-off-by: Amine RACHYD <aminerachyd99@gmail.com>

* Changes for multiarch pipeline

Pipeline no longer expects x86, Z and Power cluster API servers URLs,
task will fetch them locally from secrets.

Signed-off-by: Amine RACHYD <aminerachyd99@gmail.com>

* Updated pipeline

Signed-off-by: Amine RACHYD <aminerachyd99@gmail.com>

* Changes

Added manifest task file.
Removed code-test task from general pipeline, code-test "should" be
language specific.

Signed-off-by: Amine RACHYD <aminerachyd99@gmail.com>

* Fixed bug on task

Signed-off-by: Amine RACHYD <aminerachyd99@gmail.com>

* Build namespace on remote cluster picked up auto

Remote pipeline picks up the namespace of the build namespace on the
remote cluster automatically from variable inside the running pod.
The build namespace (XXX-dev project) should be the same on the dev
cluster as on the workload cluster.

Signed-off-by: Amine RACHYD <aminerachyd99@gmail.com>

* Fixed bug

Signed-off-by: Amine RACHYD <aminerachyd99@gmail.com>

* Changed manifest task name

Signed-off-by: Amine RACHYD <aminerachyd99@gmail.com>

* Fixed deploy task env

Signed-off-by: Amine RACHYD <aminerachyd99@gmail.com>

* Fixed deploy task bug

Signed-off-by: Amine RACHYD <aminerachyd99@gmail.com>

* Fixed deploy task bug

Signed-off-by: Amine RACHYD <aminerachyd99@gmail.com>

* Changed tools image health check task

Signed-off-by: Amine RACHYD <aminerachyd99@gmail.com>

* Changed tools image setup task

Signed-off-by: Amine RACHYD <aminerachyd99@gmail.com>

* Changed tools image

Uses image under cloudnativetoolkit org

Signed-off-by: Amine RACHYD <aminerachyd99@gmail.com>

Signed-off-by: Tim Robinson <timroster@gmail.com>
Signed-off-by: Amine RACHYD <aminerachyd99@gmail.com>
Signed-off-by: Brian Innes <binnes@uk.ibm.com>
Co-authored-by: Tim Robinson <timroster@gmail.com>
Co-authored-by: Brian Innes <binnes@users.noreply.github.com>

diff --git a/tasks/5-health-check.yaml b/tasks/5-health-check.yaml
--- a/tasks/5-health-check.yaml
+++ b/tasks/5-health-check.yaml
@@ -33,54 +33,73 @@ spec:
     - name: health-check
       image: $(params.tools-image)
       script: |
-          #!/usr/bin/env bash
-          set -x
+        #!/usr/bin/env bash
+        set -x
 
-          URL="$(params.health-url)"
-          CURL_FLAGS="$(params.health-curl)"
+        URL="$(params.health-url)"
+        CURL_FLAGS="$(params.health-curl)"
 
-          if [[ -z "${URL}" ]]; then
-            APP_NAMESPACE="$(params.app-namespace)"
-            APP_NAME="$(params.app-name)"
-            PROTOCOL="$(params.health-protocol)"
-            INGRESS_TYPE="$(params.deploy-ingress-type)"
-            HEALTH_ENDPOINT="$(params.health-endpoint)"
+        if [[ -z "${URL}" ]]; then
+          APP_NAMESPACE="$(params.app-namespace)"
+          APP_NAME="$(params.app-name)"
+          PROTOCOL="$(params.health-protocol)"
+          INGRESS_TYPE="$(params.deploy-ingress-type)"
+          HEALTH_ENDPOINT="$(params.health-endpoint)"
 
-            echo "resource-type: $(params.resource-type)"
+          echo "resource-type: $(params.resource-type)"
 
-            if [[ "$(params.resource-type)" == *"integrationserver"* ]]; then
-                HOST=$(kubectl get route/${APP_NAME}-${PROTOCOL} --namespace ${APP_NAMESPACE} --output=jsonpath='{ .spec.host }')
-                if [[ -z "${PROTOCOL}" ]]; then
-                  PROTOCOL="https"
-                fi
-            elif [[ "${INGRESS_TYPE}" == "route" ]]; then
-                HOST=$(kubectl get route/${APP_NAME} --namespace ${APP_NAMESPACE} --output=jsonpath='{ .spec.host }')
-                if [[ -z "${PROTOCOL}" ]]; then
-                  PROTOCOL="https"
-                fi
-            else
-                HOST=$(kubectl get ingress/${APP_NAME} --namespace ${APP_NAMESPACE} --output=jsonpath='{ .spec.rules[0].host }')
-                if [[ -z "${PROTOCOL}" ]]; then
-                  PROTOCOL="http"
-                fi
-            fi
-
-            URL="${PROTOCOL}://${HOST}${HEALTH_ENDPOINT}"
-
+          if [[ "$(params.resource-type)" == *"integrationserver"* ]]; then
+              HOST=$(kubectl get route/${APP_NAME}-${PROTOCOL} --namespace ${APP_NAMESPACE} --output=jsonpath='{ .spec.host }')
+              if [[ -z "${PROTOCOL}" ]]; then
+                PROTOCOL="https"
+              fi
+          elif [[ "${INGRESS_TYPE}" == "route" ]]; then
+              HOST=$(kubectl get route/${APP_NAME} --namespace ${APP_NAMESPACE} --output=jsonpath='{ .spec.host }')
+              if [[ -z "${PROTOCOL}" ]]; then
+                PROTOCOL="https"
+              fi
+          else
+              HOST=$(kubectl get ingress/${APP_NAME} --namespace ${APP_NAMESPACE} --output=jsonpath='{ .spec.rules[0].host }')
+              if [[ -z "${PROTOCOL}" ]]; then
+                PROTOCOL="http"
+              fi
           fi
 
-          sleep_countdown=5
-          # sleep for 10 seconds to allow enough time for the server to start
-          sleep 10
-          echo "Health check start"
-          while [[ $(curl ${CURL_FLAGS} -sL -w "%{http_code}\\n" "${URL}" -o /dev/null --connect-timeout 3 --max-time 5 --retry 3 --retry-max-time 30) != "200" ]]; do
-              sleep 30
-              echo "Health check failure. Remaining retries: $sleep_countdown"
-              sleep_countdown=$((sleep_countdown-1))
-              if [[ $sleep_countdown -eq 0 ]]; then
-                      echo "Could not reach health endpoint: ${URL}"
-                      exit 1;
-              fi
-          done
-          echo "Successfully reached health endpoint: ${URL}"
-          echo "====================================================================="
+          URL="${PROTOCOL}://${HOST}${HEALTH_ENDPOINT}"
+
+        fi
+
+        sleep_countdown=5
+        # sleep for 10 seconds to allow enough time for the server to start
+        sleep 10
+        echo "Health check start"
+        if [[ "${PROTOCOL}" == "grpc" ]]; then
+            echo "grpc protocol"
+            GRPC_ADDR="${APP_NAME}:$(kubectl get service ${APP_NAME} -n ${APP_NAMESPACE} --output=jsonpath='{ .spec.ports[0].port }')"
+            grpc_health_probe -addr ${GRPC_ADDR}
+            while [[ $? -ne 0 ]]; do
+                sleep 30
+                echo "Health check failure. Remaining retries: $sleep_countdown"
+                sleep_countdown=$((sleep_countdown-1))
+                if [[ $sleep_countdown -eq 0 ]]; then
+                        echo "Could not reach health endpoint: ${URL}"
+                        exit 1;
+                fi
+                grpc_health_probe -addr ${GRPC_ADDR}
+            done
+        elif [[ "${PROTOCOL}" == "https" ]]; then
+            while [[ $(curl ${CURL_FLAGS} -sL -w "%{http_code}\\n" "${URL}" -o /dev/null --connect-timeout 3 --max-time 5 --retry 3 --retry-max-time 30) != "200" ]]; do
+                sleep 30
+                echo "Health check failure. Remaining retries: $sleep_countdown"
+                sleep_countdown=$((sleep_countdown-1))
+                if [[ $sleep_countdown -eq 0 ]]; then
+                        echo "Could not reach health endpoint: ${URL}"
+                        exit 1;
+                fi
+            done
+        else
+            echo "Health check failure. Protocol not supported: ${PROTOCOL}"
+            exit 1;
+        fi
+        echo "Successfully reached health endpoint: ${URL}"
+        echo "====================================================================="
